module.exports = {
    'extends': 'eslint:recommended',
    'rules': {
        'indent': [2, 4],
        'quotes': [2, 'single'],
        'linebreak-style': [2, 'unix'],
        'semi': [2, 'always'],
        'array-bracket-spacing': [2, 'never'],
        'block-scoped-var': 1,
        'block-spacing': [2, 'always'],
        'brace-style': [2, '1tbs', { allowSingleLine: true }],
        'camelcase': 2,
        "comma-dangle": [2, "only-multiline"],
        "comma-spacing": [2, { "after": true, "before": false }],
        "comma-style": [2, "last"],
        'curly': 2,
        'dot-notation': 1,
        'dot-location': [2, 'property'],
        'eqeqeq': [2, 'allow-null'],
        'global-require': 1,
        'guard-for-in': 2,
        'key-spacing': [2, { beforeColon: true, afterColon: false }],
        'max-len': [1, 120, 4, { ignoreTrailingComments: true, ignoreUrls: true }],
        'no-caller': 2,
        'no-eval': 2,
        'no-extend-native': 2,
        'no-extra-bind': 2,
        'no-invalid-this': 1,
        'no-magic-numbers': [1, { ignoreArrayIndexes: true }],
        'no-mixed-requires': 1,
        'no-multi-spaces': 2,
        'no-trailing-spaces': 2,
        'no-throw-literal': 2,
        'radix': 2,
        'yoda': [2, 'never']
    }
};
